# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomTextView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CustomTextView
pod 'SDAutoLayout', '~> 2.1.0’

  target 'CustomTextViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomTextViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
